name: Test Internal Links

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run link checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose README.md docs/
